# Car Price Exploratory Data Analysis

## Pakacges

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
car_prices_df = pd.read_csv ('Automobile_data.csv')

## View Data Set

In [10]:
# Dimension of data frame
car_prices_df.shape
# Create a copy as a standard practice
data = car_prices_df.copy()
print(f" There are {data.shape[0]} rows and {data.shape[1]} columns.")
# View Data set
data.head(5)

 There are 205 rows and 26 columns.

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [14]:
# Correct the columns names & Data str format
  ## Uppercase & replace('-', '_')
data.columns = data.columns.str.capitalize()
# data.columns = [str.replace('_', ' ') for str in columns]
data.head(5)

# data = data.applymap(lambda s: s.capitalize() if type(s) == str else s)
# data['Make'] = data['Make'].str.upper()
# data['Aspiration'] = data['Aspiration'].str.upper()
# # data['Drive wheels'] = data['Drive wheels'].str.upper()
# data['Fuel system'] = data['Fuel system'].str.upper()

,Symboling,Normalized-losses,Make,Fuel-type,Aspiration,Num-of-doors,Body-style,Drive-wheels,Engine-location,Wheel-base,...,Engine-size,Fuel-system,Bore,Stroke,Compression-ratio,Horsepower,Peak-rpm,City-mpg,Highway-mpg,Price
0,3,?,ALFA-ROMERO,gas,STD,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,ALFA-ROMERO,gas,STD,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,ALFA-ROMERO,gas,STD,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,AUDI,gas,STD,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,AUDI,gas,STD,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [16]:
data.shape

(205, 26)